Comparision/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from django.conf import urls

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('', include('shop.urls')),
                  path('accounts/', include('django.contrib.auth.urls')),

              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shop/urls.py
from django.urls import path
from .views import *

# homepage, category_wise, product_detail, register, search

app_name = 'shop'

urlpatterns = [
    path('', homepage, name='homepage'),
    path('category/<str:category_slug>', category_wise, name='category_wise'),
    path('register', register, name='register'),
    path('product/<str:product_slug>', product_detail, name='product_detail'),
    path('search', search, name='search'),
    path('products', products, name='products'),
    path('scrape_fun/<int:id>', scrap_fun, name='scrape_fun'),
    path('cart', CartView.as_view(), name='cart'),
    path('remove_product/<int:id>', remove, name='remove_product')
]

shop/models.py
from django.db import models
from autoslug import AutoSlugField
from django.contrib.auth.models import User
from ckeditor.fields import RichTextField


# Create your models here.
class Category(models.Model):
    title = models.CharField(max_length=20)
    slug = AutoSlugField(populate_from='title')

    class Meta:
        verbose_name_plural = 'Categories'

    def __str__(self):
        return self.title


class Product(models.Model):
    title = models.CharField(max_length=20)
    slug = AutoSlugField(populate_from='title')
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    image = models.ImageField()
    brand_name = models.CharField(max_length=20)
    price = models.FloatField(blank=True)
    details = models.TextField(blank=True)


class ProductAttribute(models.Model):
    key = models.CharField(max_length=20)
    value = models.CharField(max_length=50)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)


class ProductReview(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.DO_NOTHING)
    rating = models.IntegerField()
    comment = models.TextField()

    def rating_range(self):
        return range(self.rating)


class Scrapy(models.Model):
    products = models.ForeignKey(Product, on_delete=models.CASCADE)
    daraz_price = models.FloatField(null=True)
    sastodeal_price = models.FloatField(null=True)
    esewa_price = models.FloatField(null=True)
    date_time = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name_plural = 'Scrapies'

    def __str__(self):
        return self.products.title


class Cart(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    qty = models.IntegerField()

    def total(self):
        return self.product.price * self.qty

    def __str__(self):
        return self.product.title


class AboutUs(models.Model):
    content = RichTextField()
    pub_date = models.DateField(auto_now=True)

    class Meta:
        verbose_name_plural = 'AboutUs'

    def __str__(self):
        return self.pub_date



shop/forms.py
from django.forms import ModelForm
from .models import ProductReview
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class ProductReviewForm(ModelForm):
    class Meta:
        model = ProductReview
        fields = ['comment', 'rating']


class SignUpForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'email', 'password1', 'password2']

shop/views.py
import self as self
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render, redirect, get_object_or_404
from cms.models import Banner
from .models import *
from django.views import View
from .models import Category, Product, Scrapy, Cart
from django.contrib.auth.forms import UserCreationForm
from .forms import ProductReviewForm, SignUpForm
from django.db.models import Q
from django.contrib import messages
from django.http import HttpResponseRedirect
import requests
from bs4 import BeautifulSoup
from selenium import webdriver
from datetime import datetime
import os
from django.core.paginator import Paginator
from django.views.generic import ListView

os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'Comparision00.settings')

import django

django.setup()


# Create your views here.

def homepage(request):
    categories = Category.objects.all()
    banners = Banner.objects.all()
    products = Product.objects.order_by('-id')[:10]
    paginator = Paginator(products, 1)
    page = request.GET.get('page')
    posts = paginator.get_page(page)
    context = {
        'categories': categories,
        'banners': banners,
        'posts': posts,

    }
    return render(request, 'homepage.html', context)


def category_wise(request, category_slug):
    category = Category.objects.get(slug=category_slug)
    categories = Category.objects.all()

    context = {
        'categories': categories,
        'category': category,
        'products': category.product_set.all()
    }

    return render(request, 'category_wise.html', context)


def product_detail(request, product_slug):
    # def product_detail(request, id):
    # product = get_object_or_404(Product, id=
    product = Product.objects.get(slug=product_slug)
    categories = Category.objects.all()
    # scrapy = get_object_or_404(Scrapy, id=id)
    form = ProductReviewForm()

    if request.method == 'POST':
        form = ProductReviewForm(request.POST)

        if form.is_valid():
            review = form.save(commit=False)
            review.product = product
            review.user = request.user
            review.save()

    context = {
        'product': product,
        'categories': categories,
        'form': form,

    }

    return render(request, 'product-detail.html', context)


def register(request):
    if request.method == 'POST':
        form = SignUpForm(request.POST)

        if form.is_valid():
            form.save()
            return redirect('login')
    else:
        form = SignUpForm()

    context = {
        'form': form
    }

    return render(request, 'registration/register.html', context)


def search(request):
    if request.method == 'POST':
        search_text = request.POST['search']
        products = Product.objects.filter(Q(title__contains=search_text))

        if products:
            context = {
                'search_text': search_text,
                'products': products
            }
            return render(request, 'search.html', context)
        else:
            messages.error(request, 'No result found !!')
    else:
        return HttpResponseRedirect('/homepage/')
    return render(request, 'homepage.html')


def products(request):
    products = Product.objects.order_by('-id')[:10]
    context = {

        'products': products
    }

    return render(request, 'products.html', context)


def scrap_fun(request, id):
    product_obj = get_object_or_404(Product, id=id)
    print(product_obj.title)

    product_name = product_obj.title

    product_name = product_name.lower()
    style1 = product_name.replace(' ', '%20')
    style2 = product_name.replace(' ', '+')

    ### For scrapping from daraz.com.np
    d_browser = webdriver.PhantomJS()
    request = d_browser.get("https://www.daraz.com.np/catalog/?q={}&sort=priceasc".format(style1))
    page = BeautifulSoup(d_browser.page_source, "html.parser")
    element = page.find("span", {"class": "c13VH6"})
    if element is not None:
        d_price_string = element.text.strip()
        d_price_num = float(d_price_string[4:].replace(',', ''))
        print("Price @ Daraz is Rs. {}".format(d_price_num))
    else:
        d_price_num = None
        print("Product Not Available @ SastoDeal")
    d_browser.close()

    ### For scrapping from sastodeal.com
    s_browser = webdriver.PhantomJS()
    request = s_browser.get(
        "https://www.sastodeal.com/search.html?q={}&idx=sastodeal_products_price_ascending".format(style1))
    page = BeautifulSoup(s_browser.page_source, "html.parser")
    element = page.find("div", {"class": "product-price"})
    if element is not None:
        s_price_string = element.text.split()[1]
        s_price_num = float(s_price_string[:-2].replace(',', ''))
        print("Price @ SastoDeal is Rs. {}".format(s_price_num))
    else:
        s_price_num = None
        print("Product Not Available @ SastoDeal")
    s_browser.close()

    ### For scrapping from esewapasal.com
    request = requests.get(
        "https://www.esewapasal.com/catalogsearch/result/index/?product_list_order=price&q={}&product_list_dir=asc".format(
            style2))
    soup = BeautifulSoup(request.content, "html.parser")
    element = soup.find("span", {"class": "price"})
    if element is not None:
        e_price_string = element.text.strip()
        e_price_num = float(e_price_string[4:].replace(',', ''))
        print("Price @ eSewaPasal is Rs. {}".format(e_price_num))
    else:
        e_price_num = None
        print("Product Not Available @ eSewaPasal")

    # d = datetime.date()
    # print(d)

    # e_product = Scrapy(esewa_price=e_price_num)
    # e_product.save()
    # print(e_price_num)
    if d_price_num or s_price_num or e_price_num:
        # messages.success(request, 'Crawling successful')
        prices = Scrapy(daraz_price=d_price_num, sastodeal_price=s_price_num, esewa_price=e_price_num, products_id=id)
        prices.save(force_insert=True)
        return HttpResponseRedirect('/products')

    else:
        messages.error(request, 'Error in crawling the data')

    return redirect('/products')


class BaseView(View):
    template_context = {
        'categories': Category.objects.order_by('title').all(),
        # here if we give Category.objects.all() it will load but without ordering by title

    }


class CartView(LoginRequiredMixin,
               BaseView):

    def get(self, request):
        self.template_context['cart_items'] = Cart.objects.filter(user=request.user).order_by('-id')
        self.template_context['latest_products'] = Product.objects.order_by('-id')[:5]
        self.template_context['intrested_products'] = Product.objects.order_by('?')[:2]

        total_amount = 0

        for cart_item in self.template_context['cart_items']:
            total_amount += cart_item.total()
        self.template_context['total_amount'] = total_amount
        return render(request, 'cart.html', self.template_context)

    def post(self, request):
        item = Cart()
        product = Product.objects.get(pk=request.POST.get('product_id'))
        item.product = product
        item.qty = request.POST.get('qty')
        item.user = request.user
        item.save()
        return redirect('/cart')


def remove(request, id):
    Cart.objects.filter(id=id).delete()
    return redirect('/cart')


class ChartDisplay(BaseView):
    model = Product
    template_name = 'shop/products.html'

    def get_context_data(self, **kwargs):
        context = super(ChartDisplay, self).get_context_data(*kwargs)
        print(context)
        priceDate = Scrapy.objects.filter(product__Scrapy__product=context['product']).distinct()
        date = list(Scrapy.value_list('date_time', flat=True).distinct().order_by('date_time'))
        price = list(Scrapy.values_list('price', flat=True).order_by('date_time').distinct())
        context['data'] = zip(date, price)
        return context

shop/templates/cart.html
{% extends 'base.html' %}
{% load thumbnail %}

{% block content %}

    <div class="product-big-title-area">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <div class="product-bit-title text-center">
                        <h2>Shopping Cart</h2>
                    </div>
                </div>
            </div>
        </div>
    </div> <!-- End Page title area -->


    <div class="single-product-area">
        <div class="zigzag-bottom"></div>
        <div class="container">
            <div class="row">
                <div class="col-md-8">
                    <div class="product-content-right">
                        <div class="woocommerce">
                            <form method="post" action="#">
                                <table cellspacing="0" class="shop_table cart">
                                    <thead>
                                    <tr>
                                        <th class="product-remove">&nbsp;</th>
                                        <th class="product-thumbnail">&nbsp;</th>
                                        <th class="product-name">Product</th>
                                        <th class="product-price">Price</th>
                                        <th class="product-quantity">Quantity</th>
                                        <th class="product-subtotal">Total</th>
                                    </tr>
                                    </thead>
                                    <tbody>
                                    {% for cart_item in cart_items %}
                                        <tr class="cart_item">
                                            <td class="product-remove">
                                                <a title="Remove this item" class="remove"
                                                   href="{% url 'shop:remove_product' cart_item.id %}">×</a>
                                            </td>

                                            <td class="product-thumbnail">
                                                <a href="{% url 'shop:product_detail' cart_item.product.slug %}">
                                                    {% thumbnail cart_item.product.image.image "100x100" crop="center" as im %}
                                                        <img src="{{ im.url }}" width="145" height="145"
                                                             alt="poster_1_up" class="shop_thumbnail">
                                                    {% endthumbnail %}</a>

                                            </td>

                                            <td class="product-name">
                                                <a href="{% url 'shop:product_detail' cart_item.product.slug %}">{{ cart_item.product.title }}</a>
                                            </td>

                                            <td class="product-price">
                                                <span class="amount">{{ cart_item.product.price }}</span>
                                            </td>

                                            <td class="product-quantity">
                                                <div class="quantity buttons_added">

                                                   {{ cart_item.qty }}
                                                </div>
                                            </td>

                                            <td class="product-subtotal">
                                                <span class="amount">{{ cart_item.total }}</span>
                                                {# here total is function in cart model #}
                                            </td>
                                        </tr>

                                    {% endfor %}


                                    <div class="cart_totals ">
                                        <h2>Cart Totals</h2>

                                        <table cellspacing="0">
                                            <tbody>
                                            <tr class="cart-subtotal">
                                                <th>Cart Total</th>
                                                <td><span class="amount">Rs. {{ total_amount }}</span></td>
                                            </tr>

                                            </tbody>

                                        </table>
                                    </div>
                                    </tbody>
                                </table>

                            </form>

                            {#                            <div class="cart-collaterals">#}
                            {##}
                            {##}
                            {#                                <div class="cross-sells">#}
                            {#                                    <h2>You may be interested in...</h2>#}
                            {#                                    <ul class="products">#}
                            {#                                        {% for a_product in intrested_products %}#}
                            {#                                            <li class="product">#}
                            {#                                                <a href="{% url 'shop:product_detail' a_product.slug %}">#}
                            {#                                                    {% thumbnail a_product.image.image "195x243" crop="center" as im %}#}
                            {#                                                        <img src="{{ im.url }}" width="325"#}
                            {#                                                             height="325" class="attachment-shop_catalog wp-post-image">#}
                            {#                                                    {% endthumbnail %}#}
                            {##}
                            {#                                                    <h3>{{ a_product.title }}</h3>#}
                            {#                                                    <span class="price"><span#}
                            {#                                                            class="amount">Rs. {{ a_product.price }}</span></span>#}
                            {#                                                </a>#}
                            {##}
                            {#                                                <a class="add_to_cart_button" data-quantity="1" data-product_sku=""#}
                            {#                                                   data-product_id="22" rel="nofollow"#}
                            {#                                                   href="{% url 'shop:product_detail' a_product %}">Select#}
                            {#                                                    options</a>#}
                            {#                                            </li>#}
                            {#                                        {% endfor %}#}
                            {##}
                            {#                                    </ul>#}
                            {#                                </div>#}
                            {##}
                            {##}
                            {#                                <div class="cart_totals ">#}
                            {#                                    <h2>Cart Totals</h2>#}
                            {##}
                            {#                                    <table cellspacing="0">#}
                            {#                                        <tbody>#}
                            {#                                        <tr class="cart-subtotal">#}
                            {#                                            <th>Cart Subtotal</th>#}
                            {#                                            <td><span class="amount">Rs. {{ total_amount }}</span></td>#}
                            {#                                        </tr>#}
                            {##}
                            {#                                        <tr class="shipping">#}
                            {#                                            <th>Shipping and Handling</th>#}
                            {#                                            <td>Free Shipping</td>#}
                            {#                                        </tr>#}
                            {##}
                            {#                                        <tr class="order-total">#}
                            {#                                            <th>Order Total</th>#}
                            {#                                            <td><strong><span class="amount">{{ total_amount }}</span></strong></td>#}
                            {#                                        </tr>#}
                            {#                                        </tbody>#}
                            {#                                    </table>#}
                            {#                                </div>#}
                            {##}
                            {##}
                            {#                            </div>#}
                            {#                        </div>#}
                            {#                    </div>#}
                            {#                </div>#}
                            {#                <div class="col-md-4">#}
                            {#                    <div class="single-sidebar">#}
                            {#                        <h2 class="sidebar-title">Products</h2>#}
                            {#                        {% for a_product in latest_products %}#}
                            {#                            <div class="thubmnail-recent">#}
                            {##}
                            {#                                {% thumbnail a_product.image.image "190x190" crop="center" as im %}#}
                            {#                                    <img src="{{ im.url }}" class="recent-thumb">#}
                            {#                                {% endthumbnail %}#}
                            {#                                <h2>#}
                            {#                                    <a href="{% url 'shop:product_detail' a_product.slug %}">{{ a_product.title }}</a>#}
                            {#                                </h2>#}
                            {#                                <div class="product-sidebar-price">#}
                            {#                                    <ins>${{ a_product.price }}</ins>#}
                            {#                                </div>#}
                            {#                            </div>#}
                            {#                        {% endfor %}#}
                        </div>
                    </div>
                </div>
            </div>
        </div>

{% endblock %}

shop/templates/product-detail.html
{% extends 'base.html' %}
{% load thumbnail %}

{% block content %}
    <div class="product product-details clearfix">
        <div class="col-md-6">
            <div id="product-main-view">
                <div class="product-view">
                    {% thumbnail product.image "1200x1200" crop="center" as im %}
                        <img src="{{ im.url }}" alt="">
                    {% endthumbnail %}
                </div>

            </div>
        </div>
        <div class="col-md-6">
            <div class="product-body">
                <h2 class="product-name display-2">{{ product.title }}</h2>
                <h3 class="product-price">Rs.{{ product.price }} /-</h3>
                <div>
                    <div class="product-rating">
                        <i class="fa fa-star"></i>
                        <i class="fa fa-star"></i>
                        <i class="fa fa-star"></i>
                        <i class="fa fa-star"></i>
                        <i class="fa fa-star-o empty"></i>
                    </div>
                    <a href="#">{{ product.productreview_set.count }} Review(s) / Add Review</a>
                </div>
                <p><strong>Brand:</strong> {{ product.brand_name }}</p>
                <p><strong>Product Details</strong><br><br>{{ product.details | safe }}</p>
                <br>

                <table>
                    <tr>
                        <th>Our Price</th>
                        <th>Daraz Price</th>
                        <th>Sastodeal Price</th>
                        <th>E-sewa Pasal Price</th>
                    </tr>
                    <tr>
                        <td>{{ product.price }}</td>
                        <td>{{ product.scrapy_set.first.daraz_price }}</td>
                        <td>{{ product.scrapy_set.first.sastodeal_price }}</td>
                        <td>{{ product.scrapy_set.first.esewa_price }}</td>
                    </tr>
                </table>
                <br>

                <div class="product-btns">
                    <form action="{% url 'shop:cart' %}" class="cart" method="post">
                        {% csrf_token %}
                        <input type="hidden" name="product_id" value="{{ product.id }}">
                        <div class="quantity">
                            <input type="number" size="4" class="input-text qty text main-btn icon-btn " title="qty"
                                   value="1" name="qty" min="1" step="1 " required>
                            <button class="primary-btn add-to-cart"><i class="fa fa-shopping-cart"></i> Add to Cart
                            </button>
                        </div>
                    </form>
                </div>
            </div>
            <div class="col-md-12">
                <div class="product-tab">
                    <ul class="tab-nav">
                        <li class="active"><a data-toggle="tab" href="#tab1">Description</a></li>
                        <li><a data-toggle="tab" href="#tab2">Reviews (3)</a></li>
                    </ul>
                    <div class="tab-content">
                        <div id="tab1" class="tab-pane fade in active">
                            {{ product.details }}
                        </div>
                        <div id="tab2" class="tab-pane fade in">

                            <div class="row">
                                <div class="col-md-6">
                                    <div class="product-reviews">

                                        {% for review in product.productreview_set.all %}
                                            <div class="single-review">
                                                <div class="review-heading">
                                                    <div><a href="#"><i
                                                            class="fa fa-user-o"></i> {{ review.user.username }}
                                                    </a></div>

                                                    <div class="review-rating pull-right">

                                                        {% for i in review.rating_range %}
                                                            <i class="fa fa-star"></i>
                                                        {% endfor %}
                                                    </div>

                                                </div>
                                                <div class="review-body">
                                                    <p>{{ review.comment }}</p>
                                                </div>
                                            </div>
                                        {% endfor %}

                                    </div>
                                </div>
                                {% if request.user.is_authenticated %}
                                    <div class="col-md-6">
                                        <h4 class="text-uppercase">Write Your Review</h4>
                                        <form class="review-form" method="POST"
                                              action="{% url 'shop:product_detail' product.slug %}">

                                            {% csrf_token %}

                                            {% if form.errors %}
                                                <p style="color: red">Please fill all fields</p>
                                            {% endif %}

                                            <div class="form-group">
                                                <textarea name="comment" class="input"
                                                          placeholder="Your review"></textarea>
                                            </div>
                                            <div class="form-group">
                                                <div class="input-rating">
                                                    <strong class="text-uppercase">Your Rating: </strong>
                                                    <div class="stars">
                                                        <input type="radio" id="star5" name="rating" value="5"/><label
                                                            for="star5"></label>
                                                        <input type="radio" id="star4" name="rating" value="4"/><label
                                                            for="star4"></label>
                                                        <input type="radio" id="star3" name="rating" value="3"/><label
                                                            for="star3"></label>
                                                        <input type="radio" id="star2" name="rating" value="2"/><label
                                                            for="star2"></label>
                                                        <input type="radio" id="star1" name="rating" value="1"/><label
                                                            for="star1"></label>
                                                    </div>
                                                </div>
                                            </div>
                                            <button class="primary-btn">Submit</button>
                                        </form>
                                    </div>
                                {% endif %}
                            </div>


                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div id="tab2" class="tab-pane fade in">
        <div class="container-fluid">
            <div class="row">
                <div id="chart_div">
                    {% include 'google_charts.html' %}
                </div>
            </div>
        </div>
    </div>


{% endblock %}

shop/templates/test.html
{% extends 'base.html' %}

{% block content %}
    TESTING TESTING
{% endblock %}